### ISSUE TITLE
Multiple line comments format

### ISSUE THREAD

**Issue by mirkobrombin** [hersel91/nebulabot#3]
https://github.com/hersel91/nebulabot/blob/2e96388d0fd61e9aa952a734535166a87f8d6ffc/nebula.py#L18

In python use multiple line format for big text.
https://realpython.com/python-comments-guide/

Every function should be explained on top.

**Comment by hersel91** [comment]
We are also proceeding to refactor the comments

**Comment by mirkobrombin** [comment]
Issues should be closed when problems have been fixed. Quote an issue in the commit to create a fix history.
